
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  build:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      # TODO Use composite GitHub action when sharing across organizations is allowed
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v3
        with: { java-version: 17, distribution: temurin, cache: gradle }

      # PROCESS
      - name: Build Project
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build
      - name: Log Build (ON FAILURE)
        if: matrix.os == 'ubuntu-latest' && failure()
        run: ./gradlew --info --stacktrace build
      - name: Build Project WITHOUT Docker
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew build -x store_mongodb:test -x messaging_rabbitmq:test
      - name: Log Build WITHOUT Docker (ON FAILURE)
        if: matrix.os != 'ubuntu-latest' && failure()
        run: ./gradlew -is build -x store_mongodb:test -x messaging_rabbitmq:test

  test_publishing:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v3
        with: { java-version: 17, distribution: temurin, cache: gradle }

      # PROCESS
      - name: Test Publishing
        run: ./gradlew --no-daemon publishToMavenLocal -x test
      - name: Test Publishing (ON FAILURE)
        if: failure()
        run: ./gradlew --info --stacktrace --no-daemon publishToMavenLocal -x test
