
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          exempt-issue-labels: pinned
          include-only-assigned: true
          days-before-stale: 90
          days-before-close: 14
          days-before-pr-close: -1
          stale-pr-message: This PR is stale because it has been open 45 days with no activity.
          stale-issue-message:
            "This issue is stale because it has been open 90 days with no activity. Remove stale
            label or comment or this will be closed in 14 days."
          close-issue-message:
            "This issue was closed because it has been stalled for 14 days with no activity."

  build:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      # TODO Use composite GitHub action when sharing across organizations is allowed
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Install Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: native-image,llvm
          cache: gradle

      # PROCESS
      - name: Build Project
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew build
      - name: Log Build (ON FAILURE)
        if: matrix.os == 'ubuntu-latest' && failure()
        run: ./gradlew --info --stacktrace build
      - name: Build Project WITHOUT Docker
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew build -x store_mongodb:test -x messaging_rabbitmq:test
      - name: Log Build WITHOUT Docker (ON FAILURE)
        if: matrix.os != 'ubuntu-latest' && failure()
        run: ./gradlew -is build -x store_mongodb:test -x messaging_rabbitmq:test

  test_publishing:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Install Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: native-image,llvm
          cache: gradle

      # PROCESS
      - name: Test Publishing
        run: ./gradlew --no-daemon publishToMavenLocal -x test
      - name: Test Publishing (ON FAILURE)
        if: failure()
        run: ./gradlew --info --stacktrace --no-daemon publishToMavenLocal -x test
