
name: Pull Request

on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with: { java-version: 11, distribution: temurin, cache: gradle }

      # PROCESS
      - name: Build Project
        run: ./gradlew build
      - name: Log Build (ON FAILURE)
        if: failure()
        run: ./gradlew --info --stacktrace build

  test_publishing:
    name: Test Publishing
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with: { java-version: 11, distribution: temurin, cache: gradle }

      # PROCESS
      - name: Test Publishing
        run: ./gradlew --no-daemon publishToMavenLocal
