
name: Pull Request

on:
  - pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      check_directory: args/build

  native_test:
    name: Native Test
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      check_directory: args/build
      tasks: nativeTest

  test_publishing:
    name: Test Publishing
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      check_directory: args/build
      tasks: publishToMavenLocal -x test
