
name: Pull Request

on:
  - pull_request

jobs:
  build:
    name: Build
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      check_directory: args/build

  test_publishing:
    name: Test Publishing
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      check_directory: args/build
      tasks: publishToMavenLocal
