
name: Push

on:
  push:
    branches-ignore: [ master ]

jobs:
  build:
    name: Build
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      check_directory: args/build
