
name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Build Project
        run: ./gradlew build
      - name: Log Build (ON FAILURE)
        if: failure()
        run: ./gradlew --info --stacktrace build

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Publish Packages
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          export REMOTE="https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote set-url origin "$REMOTE"
          git config --global user.email "juanjoaguililla@gmail.com"
          git config --global user.name "jaguililla"
          ./gradlew --info --no-daemon -x test release

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}
